### ISSUE TITLE
Feature request: use vim.ui.select

### ISSUE THREAD

**Issue by andrewferrier** [wintermute-cell/gitignore.nvim#1]
Hi - I think gitignore.nvim is a really good idea. However, for me at least, it's a shame that it depends on `telescope.nvim`. You might want to consider refactoring it to support `vim.ui.select` instead - https://neovim.io/doc/user/lua.html#lua-ui. This is a generic layer in NeoVim intended as an abstraction between things that need selections and selector mechanisms like telescope. See https://github.com/stevearc/dressing.nvim for a better explanation.

**Comment by wintermute-cell** [comment]
Hey, thanks you for the suggestion.

I was originally, before deciding on telescope, planning on using `vim.ui.select`, as I would've preferred an option without dependencies as well.

The issue with this is the lack of multi selection (This can be fixed by running multiple selections in a row) and most notably the inappropriate interface for long lists without the use of a prettyfication plugin like dressing.nvim. (You have to scroll through the entire list of options before making a selection, and you must select by numbers instead of name)

I was considering to alternatively allow the `:Gitignore` commands to take arguments, to skip the selection step (e.g.`:Gitignore java python ruby`). This isn't optimal in terms of discoverability, but still better UX than `vim.ui.select` in this case.

Please correct me if any of my assumptions about `vim.ui.select` are incorrect.

**Comment by hinell** [comment]
You can use <kbd>TAB</kbd> to select multiple choices (plus sign).
![image](https://user-images.githubusercontent.com/8136158/228478556-1cd9518a-554d-4765-8805-ec6638506430.png)

**Comment by andrewferrier** [comment]
> Hey, thanks you for the suggestion.
> 
> I was originally, before deciding on telescope, planning on using `vim.ui.select`, as I would've preferred an option without dependencies as well.
> 
> The issue with this is the lack of multi selection (This can be fixed by running multiple selections in a row) and most notably the inappropriate interface for long lists without the use of a prettyfication plugin like dressing.nvim. (You have to scroll through the entire list of options before making a selection, and you must select by numbers instead of name)
> 
> I was considering to alternatively allow the `:Gitignore` commands to take arguments, to skip the selection step (e.g.`:Gitignore java python ruby`). This isn't optimal in terms of discoverability, but still better UX than `vim.ui.select` in this case.
> 
> Please correct me if any of my assumptions about `vim.ui.select` are incorrect.

Fair enough, and understood, that makes sense. Well, thanks for your hard work and contribution back to the community with the plugin! Good luck with it.

**Comment by JarKz** [comment]
Hi!
There is a simple solution. Instead of making complex solution you can create a contract:
1. your plugin provide two things: list of prefixes and method, which get selected prefixes as list;
2. user can create custom selector, based on something: telescope, fzf and etc.; and user must pass non-empty list that contains selected prefixes to provided method.

But, with it we have one simple problem: check right of prefixes. I think, it is not hard to write function for checking this.

**Comment by wintermute-cell** [comment]
Solved with https://github.com/wintermute-cell/gitignore.nvim/commit/e6c3c968cdb5332760e84f2bcf3e94dd1824f9c7
