### ISSUE TITLE
Feature request: append to existing .gitignore

### ISSUE THREAD

**Issue by dhensen** [wintermute-cell/gitignore.nvim#5]
Currently if I have an existing .gitignore, if I do :Gitignore > Python. It will overwrite my current buffer. Please make it (optionally?) append instead.

**Comment by wintermute-cell** [comment]
Thank you for the suggestion!
This is now implemented in bce08fae0e1d7f5ec1093ef6f10d56391a0f318f.
From now on, the `:Gitignore` command will append by default. You can disable this behavior by setting:
```lua
vim.g.gitignore_nvim_overwrite = true
```

Additionally, since now existing gitignores are respected, you can optionally pass a path:
```vimscript
:Gitignore [path]
```
`gitignore.nvim` will then search that path for a `.gitignore` to use as a base. (Implemented in a181cd57922bce89db0b63bd9455a0d19f6b2c41)

**Comment by dhensen** [comment]
@wintermute-cell you're the best! going to try this out tonight!
